import notesData from "../data/notes.json";

/** An article from lenatriestounderstand (generated by `npm run sync-notes`). */
export type Note = {
  title: string;
  description: string;
  date: string;
  updated: string;
  track: string;
  tags: string[];
  short: boolean;
  href: string;
  image: string;
};

export const notes = notesData as Note[];
export const articles = notes.filter((n) => !n.short);
export const shorts = notes.filter((n) => n.short);

export const formatNoteDate = (iso: string) =>
  iso ? new Date(`${iso}T00:00:00`).toLocaleDateString("en-GB", { year: "numeric", month: "short" }) : "";
